# .github/workflows/keep-alive.yml
name: Keep Render Service Alive

on:
  schedule:
    # Pings plus fréquents pour tenter de garder le service actif.
    # Ces planifications combinées visent un ping toutes les 10-20 minutes environ.
    # Exécute aux minutes 7 et 37 de chaque heure.
    - cron: '7,37 * * * *'
    # Exécute aux minutes 19 et 49 de chaque heure.
    - cron: '19,49 * * * *'
    # Exécute à la minute 55 de chaque heure (pour un autre point de contact).
    - cron: '55 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest # Exécute la tâche sur une machine virtuelle Ubuntu

    steps:
      - name: Ping the website # Nom de l'étape
        # Utilise l'outil en ligne de commande 'curl' pour faire une requête HTTP GET.
        # -s: Mode silencieux (supprime la barre de progression et les messages d'erreur)
        # -S: Affiche les erreurs même en mode silencieux
        # -f: Échoue silencieusement sur les erreurs serveur (codes 4xx ou 5xx)
        # -L: Suit les redirections (utile si Render redirige HTTP vers HTTPS)
        # "${{ secrets.WEBSITE_URL }}": Utilise le secret GitHub que vous avez configuré
        # > /dev/null: Redirige la sortie standard vers /dev/null (la jette)
        # || echo "Ping failed": Si la commande curl échoue (code de retour non nul), affiche "Ping failed"
        run: curl -sSfL "${{ secrets.WEBSITE_URL }}" > /dev/null || echo "Ping failed"
